<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRsyV8bn\FitnessApi_App_AppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRsyV8bn/FitnessApi_App_AppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRsyV8bn.legacy');

    return;
}

if (!\class_exists(FitnessApi_App_AppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRsyV8bn\FitnessApi_App_AppKernelDevDebugContainer::class, FitnessApi_App_AppKernelDevDebugContainer::class, false);
}

return new \ContainerRsyV8bn\FitnessApi_App_AppKernelDevDebugContainer([
    'container.build_hash' => 'RsyV8bn',
    'container.build_id' => '390bd9d8',
    'container.build_time' => 1710868888,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRsyV8bn');
