<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK0qL11d\FitnessApi_App_AppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK0qL11d/FitnessApi_App_AppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerK0qL11d.legacy');

    return;
}

if (!\class_exists(FitnessApi_App_AppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerK0qL11d\FitnessApi_App_AppKernelDevDebugContainer::class, FitnessApi_App_AppKernelDevDebugContainer::class, false);
}

return new \ContainerK0qL11d\FitnessApi_App_AppKernelDevDebugContainer([
    'container.build_hash' => 'K0qL11d',
    'container.build_id' => 'f472ddcc',
    'container.build_time' => 1710947029,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK0qL11d');
