<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'health_get' => [[], ['ignore_monitoring' => true, '_controller' => 'FitnessApi\\App\\Controller\\HealthCheckController'], [], [['text', '/health']], [], [], []],
];
