<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO3mOSSL\FitnessApi_App_AppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO3mOSSL/FitnessApi_App_AppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerO3mOSSL.legacy');

    return;
}

if (!\class_exists(FitnessApi_App_AppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerO3mOSSL\FitnessApi_App_AppKernelDevDebugContainer::class, FitnessApi_App_AppKernelDevDebugContainer::class, false);
}

return new \ContainerO3mOSSL\FitnessApi_App_AppKernelDevDebugContainer([
    'container.build_hash' => 'O3mOSSL',
    'container.build_id' => 'bb5d9e00',
    'container.build_time' => 1710867626,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO3mOSSL');
