# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true

    Doctrine\ORM\EntityManagerInterface: '@doctrine.orm.default_entity_manager'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    FitnessApi\:
        resource: '../../src/'
    FitnessApi\App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/AppKernel.php'
    FitnessApi\Tests\:
      resource: '../../tests'
    FitnessApi\App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
