<?php

namespace ContainerRsyV8bn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_XZowc_TService extends FitnessApi_App_AppKernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.XZowc.T' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 5).'/vendor/symfony/notifier/Messenger/MessageHandler.php';

        $a = ($container->privates['texter.transports'] ?? $container->load('getTexter_TransportsService'));

        if (isset($container->privates['.messenger.handler_descriptor.XZowc.T'])) {
            return $container->privates['.messenger.handler_descriptor.XZowc.T'];
        }

        return $container->privates['.messenger.handler_descriptor.XZowc.T'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \Symfony\Component\Notifier\Messenger\MessageHandler($a), []);
    }
}
