health_get:
  path: /health
  controller: FitnessApi\App\Controller\HealthCheckController
  methods:  [GET]
  defaults:
    ignore_monitoring: true
create_user:
  path: /user/create
  controller: FitnessApi\App\Controller\User\CreateUserController
  methods:  [POST]
  defaults:
    ignore_monitoring: true
